"""Application services and deployment-specific composition roots."""

from .local import LocalPipelineRuntimeFactory
from video_preprocess.inference import (
    HTTPProviderSettings,
    InferenceDeploymentSettings,
)
from .pipeline import (
    PipelineApplicationService,
    PipelineRunRequest,
    PipelineRuntime,
    PipelineRuntimeFactory,
    PipelineServiceInputError,
    PipelineSettings,
)
from .pipeline_runs import (
    EngineRunObservation,
    LocalMediaCatalog,
    LocalPipelineProgressReader,
    LocalPipelineRunRepository,
    MediaNotFoundError,
    PipelineCapacityError,
    PipelineFailure,
    PipelineIdempotencyConflictError,
    PipelineRunNotFoundError,
    PipelineRunNotReadyError,
    PipelineRunRepository,
    PipelineRunService,
    PipelineRunServiceError,
    PipelineRunSnapshot,
    PipelineRunSubmission,
    PublicRunStatus,
)
from .query import (
    FixedQueryTargetResolver,
    LocalPipelineRunQueryResolver,
    PipelineQueryRequest,
    PipelineQueryResult,
    QueryIndexNotFoundError,
    QueryMatch,
    QueryRunNotReadyError,
    QueryService,
    QueryServiceError,
    QueryServiceInputError,
)
from .retrieval_evaluation import (
    RetrievalEvaluationCase,
    RetrievalEvaluationReport,
    evaluate_retrieval,
    load_evaluation_cases,
)

__all__ = [
    "LocalPipelineRuntimeFactory",
    "HTTPProviderSettings",
    "InferenceDeploymentSettings",
    "PipelineApplicationService",
    "PipelineRunRequest",
    "PipelineRuntime",
    "PipelineRuntimeFactory",
    "PipelineServiceInputError",
    "PipelineSettings",
    "EngineRunObservation",
    "LocalMediaCatalog",
    "LocalPipelineProgressReader",
    "LocalPipelineRunRepository",
    "MediaNotFoundError",
    "PipelineCapacityError",
    "PipelineFailure",
    "PipelineIdempotencyConflictError",
    "PipelineRunNotFoundError",
    "PipelineRunNotReadyError",
    "PipelineRunRepository",
    "PipelineRunService",
    "PipelineRunServiceError",
    "PipelineRunSnapshot",
    "PipelineRunSubmission",
    "PublicRunStatus",
    "FixedQueryTargetResolver",
    "LocalPipelineRunQueryResolver",
    "PipelineQueryRequest",
    "PipelineQueryResult",
    "QueryIndexNotFoundError",
    "QueryMatch",
    "QueryRunNotReadyError",
    "QueryService",
    "QueryServiceError",
    "QueryServiceInputError",
    "RetrievalEvaluationCase",
    "RetrievalEvaluationReport",
    "evaluate_retrieval",
    "load_evaluation_cases",
]
